language: ruby
cache: bundler
before_install: gem update bundler
install:
  - bundle install
script:
  - git remote add upstream https://$GH_TOKEN@$GH_REF
  - git fetch upstream
  - git reset upstream/gh-pages
  - rm -rf ./_site
  - bundle exec jekyll build --trace
  - git add ./_site -f
  - git config --global user.name "travis-ci"
  - git config --global user.email "travis@travis-ci.org"
  - git commit -m "Build $TRAVIS_BUILD_NUMBER"
  - git push -q upstream HEAD:gh-pages
branches:
  only:
    - archive-tags
