language: ruby
cache: bundler
before_install: gem update bundler
install:
  - bundle install
script:
  - git remote add upstream https://$GH_TOKEN@$GH_REF
  - git fetch upstream
  - rm -rf ./_site
  - git worktree add _site -B gh-pages
  - bundle exec jekyll build --trace --future
  - cd _site
  - git add --all
  - git config --global user.name "travis-ci"
  - git config --global user.email "travis@travis-ci.org"
  - git commit -m "Build $TRAVIS_BUILD_NUMBER"
  - git push upstream gh-pages -f
branches:
  only:
    - master
