title: Hyper Extended MTG
email:
description: >-
  Hyper Extended Magic the Gathering.
meta_image: /assets/img/compuserve/20181222_173749.jpg

baseurl: ""
url: "https://hextended.com"
permalink: /blog/:year/:month/:day/:title/
include:
- "_pages"
exclude:
- readme.md
- start.cmd
- start.sh
- Gemfile
- Gemfile.lock

incremental: true

twitter_username: hextended
github_username:  hypermtg
github_repo: hypermtg/hypermtg.github.io
google_analytics:
  enabled: false
  id: UA-129495562-1

markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  typographic_symbols: {hellip: ..., ndash: --}

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-octicons

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layout: archive
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    day: '/archive/:year/:month/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'
