title: Hyper Extended MTG
email:
description: >-
  Hyper Extended Magic the Gathering.
baseurl: ""
url: "https://hextended.com"
permalink: /blog/:year/:month/:day/:title/
exclude:
- readme.md

twitter_username: hextended
github_username:  hypermtg
google_analytics:
  enabled: false
  id: UA-129495562-1

markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  typographic_symbols: {hellip: ..., ndash: --}

plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-octicons
