title: Hyper Extended MTG
email:
description: >-
  Hyper Extended Magic the Gathering.
baseurl: ""
url: "hextended.com"
permalink: /blog/:year/:month/:day/:title/

twitter_username: hextended
github_username:  hypermtg
google_analytics:
    enabled: true
    id: UA-129495562-1

markdown: kramdown
plugins:
  - jekyll-feed
