title: HyperExtended MTG
email:
description: >-
  HyperExtended Magic the Gathering.
baseurl: ""
url: "hextended.com"
permalink: /blog/:year/:month/:day/:title/

twitter_username: hextended
github_username:  hypermtg

markdown: kramdown
plugins:
  - jekyll-feed
